name: Build and deploy Vite app to Azure Web App - alacancha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and build
        run: |
          cd frontend/alachancha          # 👈 ir a tu proyecto Vite
          npm ci                           # instalación limpia
          npm run build                     # genera la carpeta dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: frontend/alachancha/dist    # 👈 solo sube la carpeta dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app
          path: .                           # se descarga en el workspace raíz

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8866CFA9284E4E50A7CDB4DBD91E5D62 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F5E611B2761464A952BF53ABF740268 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6919FC5E18A4B63A8F3FB46ABD1B203 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'alacancha'
          slot-name: 'Production'
          package: .
